/**
 * Parity with the Rust engine's move generator.
 *
 * `lib/game/rules.ts` is a second implementation of the rules of Gygès. The
 * first is `MoveGen` in the `gyges` crate, which is the battle-tested one and
 * is what the bot will eventually search with. Two implementations of the same
 * rules will drift apart unless something checks — this is that something.
 *
 * `tests/fixtures/engine-moves.json` holds 300 positions and, for each, the
 * complete legal move list **as produced by the engine itself**. It was
 * generated by `gyges/examples/dump_moves.rs`, which loads each position with
 * `BoardState::from` and runs `MoveGen::gen::<GenMoves, NoQuit>()`. The
 * fixture is checked in so this test needs neither Rust nor the engine to run.
 *
 * These vectors are not illustrative — they are the specification. When this
 * test fails, this module is wrong and the engine is right, unless there is a
 * specific reason to believe otherwise.
 *
 * Regenerating: build the example in the GygesRust checkout, feed it lines of
 * "<38 digits> <player>", and store the sorted `from|to[|drop]` lists.
 *
 * Run with: npm test
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const { legalMoves, checkMoveLegality } = await import("../lib/game/rules.ts");
const { moveFromString } = await import("../lib/game/board.ts");
import type { Player } from "../lib/game/board.ts";

interface Vector {
  board: string;
  player: number;
  moves: string[];
}

const here = dirname(fileURLToPath(import.meta.url));
const vectors: Vector[] = JSON.parse(
  readFileSync(join(here, "fixtures", "engine-moves.json"), "utf8"),
);

const decode = (s: string) => Array.from(s, Number);

test("the fixture is present and substantial", () => {
  assert.ok(vectors.length >= 100, "at least 100 positions");
  const total = vectors.reduce((n, v) => n + v.moves.length, 0);
  assert.ok(total > 10000, `expected a large corpus, got ${total} moves`);
});

test("generated moves match the engine exactly, position for position", () => {
  const failures: string[] = [];

  for (const v of vectors) {
    const board = decode(v.board);
    const mine = [
      ...new Set(legalMoves(board, v.player as Player).map((m) => m.join("|"))),
    ].sort();
    const theirs = [...v.moves].sort();

    if (mine.join(",") === theirs.join(",")) continue;

    const ours = new Set(mine);
    const rust = new Set(theirs);
    failures.push(
      [
        `${v.board} player=${v.player}`,
        `  extra (we allow, engine does not): ${mine
          .filter((m) => !rust.has(m))
          .slice(0, 8)
          .join(" ")}`,
        `  missing (engine allows, we do not): ${theirs
          .filter((m) => !ours.has(m))
          .slice(0, 8)
          .join(" ")}`,
      ].join("\n"),
    );
    if (failures.length >= 5) break;
  }

  assert.equal(
    failures.length,
    0,
    `move generation diverged from the engine:\n${failures.join("\n\n")}`,
  );
});

test("every move the engine calls legal passes checkMoveLegality", () => {
  // Generation and single-move validation are separate code paths, and the
  // server uses the second one. Both must agree with the engine.
  for (const v of vectors) {
    const board = decode(v.board);
    for (const encoded of v.moves) {
      const verdict = checkMoveLegality(
        board,
        v.player as Player,
        moveFromString(encoded),
      );
      assert.ok(
        verdict.legal,
        `engine calls ${encoded} legal on ${v.board} (player ${v.player}) ` +
          `but the checker refused it: ${verdict.reason}`,
      );
    }
  }
});

test("moves the engine omits are refused by checkMoveLegality", () => {
  // The converse, sampled: for a handful of positions, every simple move that
  // the engine did not list must be rejected. This is what stops the checker
  // being permissive in a way generation happens not to exercise.
  for (const v of vectors.slice(0, 40)) {
    const board = decode(v.board);
    const legal = new Set(v.moves);

    for (let from = 0; from < 36; from++) {
      for (let to = 0; to < 38; to++) {
        const encoded = `${from}|${to}`;
        if (legal.has(encoded)) continue;
        const verdict = checkMoveLegality(
          board,
          v.player as Player,
          moveFromString(encoded),
        );
        assert.ok(
          !verdict.legal,
          `${encoded} is not in the engine's list for ${v.board} ` +
            `(player ${v.player}) but the checker allowed it`,
        );
      }
    }
  }
});
